export interface Trade {
  // Original fields
  id: string;
  date: string;
  symbol: string;
  type: 'Buy' | 'Sell';
  quantity: number;
  price: number;
  mtm_pnl: number;
  strategy: string;
  
  // All additional fields from the JSON
  uuid: string;
  created_by: string;
  created_timestamp: string;
  end_date: string | null;
  start_date: string | null;
  tenant_id: string;
  updated_by: string;
  updated_timestamp: string;
  buy_open_position: number;
  closed_pnl_today: number;
  closed_position: number;
  commodity: string;
  company: string;
  counterparty: string;
  eod_currency: string;
  eod_job_name: string;
  eod_run_date: string;
  eoduom: string;
  finance_cost: number;
  freight_cost: number;
  fx_exposure: number;
  fx_exposure_currency: string;
  insurance_cost: number;
  mtm_settlement: number;
  nbv: number;
  obligationid: string;
  other_cost: number;
  pnl_monthly: number;
  pnl_yearly: number;
  price_currency: string;
  price_exposure: number;
  profitcenter: string;
  raw_data_id: string | null;
  realised_pnl_today: number;
  realized_date: string | null;
  realized_position: number;
  sell_open_position: number;
  tax_cost: number;
  total_cost: number;
  trade_id: string;
  prev_mtm_pnl: number;
  prev_open_buy_position: number;
  prev_open_sell_position: number;
  trade_value: number;
  trader_name: string;
  prev_realised_pnl: number;
  prev_realised_postion: number;
  prev_closed_postion: number;
  total_netted_cost: number;
  total_added_cost: number;
  total_premium_discount: number;
  trade_type: string;
  trade_transaction_type: number;
  price_type: string;
  trade_date_time: string;
  parent_commodity: string | null;
  mtm_price_date: string | null;
  bulk_packed: string | null;
  incoterm: string | null;
  brand: string | null;
  grade: string | null;
  origin: string | null;
  season: string | null;
  trade_quantity: number | null;
  total_contract_qty: number | null;
  planned_quantity: number | null;
  actual_load_quantity: number | null;
  actual_unload_quantity: number | null;
  total_price_allocated_quantity: number | null;
  plan_id: string | null;
  mtmindex: string | null;
  mtm_index_period: string | null;
  basis_mtm_index_period: string | null;
  contract_month: string | null;
  premium_discount: number | null;
  market_settlement_price: number | null;
  future_market_settlement_price: number | null;
  basis_market_settlement_price: number | null;
  mtm_index_currency: string | null;
  mtm_index_uom: string | null;
  total_netted_cost_in_mtm_currency: number;
  total_added_cost_in_mtm_currency: number;
  total_cost_in_mtm_currency: number;
  trade_value_in_mtm_currency: number;
  mtm_pnl_in_mtm_currency: number;
  reporting_uom: string | null;
  trade_quantity_in_reporting_uom: number;
  obligation_quantity_in_reporting_uom: number;
  allocated_quantity_in_reporting_uom: number;
  actualized_quantity_in_reporting_uom: number;
  discharge_quantity_in_reporting_uom: number;
  priced_quantity_in_reporting_uom: number;
  un_priced_quantity_in_reporting_uom: number;
  closed_pnl_today_in_settlement: number;
  realised_pnl_today_in_settlement: number;
  provisional_pnl_in_settlement: number;
  provisional_pnl_today: number;
  basis_mtm_index_currency: string | null;
  basis_mtm_index_uom: string | null;
  invoice_currency: string | null;
  invoice_amount: number;
  actual_origin: string | null;
  basis_mtm_index: string | null;
  delivery_end_date: string | null;
  delivery_start_date: string | null;
  discharge_port: string | null;
  fx_allocation_status: string | null;
  fx_rate: number | null;
  invoice_id: string | null;
  laycan_date: string | null;
  location: string | null;
  obligation_status: string | null;
  planned_obligation_id: string | null;
  prem_currency: string | null;
  prem_uom: string | null;
  price_allocation_status: string | null;
  price_settlement_currency: string | null;
  priceuom: string | null;
  prov_price_currency: string | null;
  prov_priceuom: string | null;
  prov_trade_price: number | null;
  quantityuom: string | null;
  stock_currency: string | null;
  stock_price: number | null;
  stock_quantity: number | null;
  stock_type: string | null;
  stockuom: string | null;
  storage_location: string | null;
  trade_discharge_location: string | null;
  trade_load_location: string | null;
  trade_settlement_price: number | null;
}

export interface ColumnVisibility {
  [key: string]: boolean;
}
